# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hunt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hunt

  target 'hunt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'huntTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'hunt-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hunt-tvOS

  target 'hunt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
